
server:
  address: 0.0.0.0
  port: 8080

spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/cobranca
    username: postgres
    password: 180395Az!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: consultorialudovicense@gmail.com
    password: 032218Mi!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

asaas:
  url: https://www.asaas.com/api/v3
  token: $aact_prod_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjAzNGI2MzMxLTMwNTMtNDcxNC04ZDBjLTBhMDJlNDNlMzEwMDo6JGFhY2hfZGQ3YjJhNjctNGFmZi00ZjA4LTkyZDQtMzk5OWU1ZjZlZjBk
