server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cobranca
    username: postgres
    password: 180395Az!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: igor.diniz23@gmail.com              # altere aqui
    password: nopainnogain21         # altere aqui
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

asaas:
  url: https://sandbox.asaas.com/api/v3
  token: $aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OmI0YTIwMjllLWQyMWQtNDYyMi04MzZiLWU1ZjdiNmRiYWZjZTo6JGFhY2hfM2JkNDlmMmEtNDZiMy00YzgwLThiMmUtZWRmYTRmZmUyMGFk
